image: ruby:2.4

variables:
  JEKYLL_ENV: production

before_script:
  - bundle install

test:
  script:
    - bundle exec jekyll build

# pages:
#   stage: deploy
#   script:
#     - bundle exec jekyll build
#     - mkdir public
#     - mv _site/* public
#   artifacts:
#     paths:
#       - public
#   only:
#     - master
