title: Naturkindergarten Wildzwerge e.V.
email: mail@wildzwerge.de
description: >
  Naturkindergarten auf dem Stadtwerder in Bremen – Naturkindergarten
  Wildzwerge e.V.
baseurl: ''
url: 'http://wildzwerge.de/'

markdown: kramdown
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - README.md

sass:
  style: compressed
